import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 - Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
 */

const projects = ['nui', 'nuicss', 'utils', 'locale', 'markon'] as const;

const sidebars: SidebarsConfig = Object.fromEntries(
  projects.map((name) => [
    name,
    [
      {
        type: 'autogenerated',
        dirName: name,
      },
    ],
  ])
);

export default sidebars;
